print("hello world")
print("dev branch has been successfully build")
print("airflow infra dockerlized  ,cloudwatch infra ,azure function infra azure synapse analytics and adlsgen2 infra")
print("deploying airflowsss")
print("back")
print("new")
print("new oegg")
print("final")
print("test2")
