name: Deploy Azure Function Infrastructure

on:
  push:
    branches:
      - dev
  workflow_dispatch: # manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List terraform folder contents
        run: ls -la terraform/${{ matrix.env }}/infra

      # Login to Azure CLI (needed for az commands, optional here but good for az CLI calls)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set environment variables for Terraform Service Principal auth
      - name: Export ARM environment variables for Terraform
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Step 1: Terraform Init
      - name: Terraform Init
        working-directory: terraform/${{ matrix.env }}/infra
        run: terraform init

      # Step 2: Terraform Apply for Function Infra Only
      - name: Terraform Apply (Function Infra Only)
        if: ${{ github.ref == format('refs/heads/{0}', matrix.env) }}
        working-directory: terraform/${{ matrix.env }}/infra
        run: |
          terraform apply -auto-approve -var-file=terraform.tfvars \
            -target=azurerm_function_app.func \
            -target=azurerm_app_service_plan.func_plan \
            -target=azurerm_storage_account.func_storage

      # Step 3: Install Azure Functions Core Tools
      - name: Install Azure Functions Core Tools
        run: |
          sudo npm install -g azure-functions-core-tools@4 --unsafe-perm true

      # Step 4: Publish Azure Function Code
      - name: Publish Azure Function Code
        working-directory: function-code
        run: |
          func azure functionapp publish process-file-func --python

      # Step 5: Terraform Apply for Remaining Infra (Event Grid etc)
      - name: Terraform Apply (Remaining Infra)
        if: ${{ github.ref == format('refs/heads/{0}', matrix.env) }}
        working-directory: terraform/${{ matrix.env }}/infra
        run: terraform apply -auto-approve -var-file=terraform.tfvars
