name: Deploy Azure Function Infrastructure

on:
  push:
    branches:
      - dev
  workflow_dispatch: # allows manual trigger (can add destroy job later if needed)

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev] # match your environment naming (can add prod later)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List terraform folder contents
        run: ls -la terraform/${{ matrix.env }}/infra

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # -------------------
      # STEP 1: Deploy Infra (Function App, Plan, Storage)
      # -------------------
      - name: Terraform Init
        working-directory: terraform/${{ matrix.env }}/infra
        run: terraform init

      - name: Terraform Apply (Function Infra Only)
        if: ${{ github.ref == format('refs/heads/{0}', matrix.env) }}
        working-directory: terraform/${{ matrix.env }}/infra
        run: |
          terraform apply -auto-approve -var-file=terraform.tfvars \
            -target=azurerm_function_app.func \
            -target=azurerm_app_service_plan.func_plan \
            -target=azurerm_storage_account.func_storage \
            -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -var "azure_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -var "azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      # -------------------
      # STEP 2: Deploy Function Code (HttpTrigger1)
      # -------------------
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Functions Core Tools
        run: |
          sudo npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Publish Azure Function Code
        working-directory: function-code  # change if your function app code folder differs
        run: |
          func azure functionapp publish process-file-func --python

      # -------------------
      # STEP 3: Deploy Event Grid + Remaining Infra
      # -------------------
      - name: Terraform Apply (Remaining Infra)
        if: ${{ github.ref == format('refs/heads/{0}', matrix.env) }}
        working-directory: terraform/${{ matrix.env }}/infra
        run: |
          terraform apply -auto-approve -var-file=terraform.tfvars \
            -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -var "azure_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -var "azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
