name: Deploy Databricks Infrastructure

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name:  List terraform folder contents
        run: ls -la cicd/terraform/${{ matrix.env }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: cicd/terraform/${{ matrix.env }}
        run: terraform init

      - name: Terraform Plan
        working-directory: cicd/terraform/${{ matrix.env }}
        run: |
          terraform plan -var-file=terraform.tfvars \
          -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var "azure_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
          -var "azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
          -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Terraform Apply
        if: ${{ github.ref == format('refs/heads/{0}', matrix.env) }}
        working-directory: cicd/terraform/${{ matrix.env }}
        run: |
          terraform apply -auto-approve -var-file=terraform.tfvars \
          -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var "azure_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
          -var "azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
          -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
