name: Deploy Airflow to Azure

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: airflow-custom
  IMAGE_TAG: latest_img
  ACR_NAME: acrairflowdevhealthcare
  ACR_LOGIN_SERVER: acrairflowdevhealthcare.azurecr.io
  RESOURCE_GROUP_NAME: healthcare_project
  CONTAINER_INSTANCE_NAME: airflow-container

jobs:
  terraform-deploy:
    name: Terraform Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}

      - name: Break Terraform state blob lease if locked
        run: |
          az storage blob lease break \
            --account-name tfstate147025af \
            --container-name tfstate \
            --blob-name terraform.tfstate \
            --auth-mode login || echo "No lease to break"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform/dev/acr
        run: terraform init

      - name: Terraform Format Check
        working-directory: terraform/dev/acr
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: terraform/dev/acr
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/dev/acr
        run: |
          terraform plan \
            -input=false \
            -lock-timeout=120s \
            -var="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" \
            -var="acr_name=${{ env.ACR_NAME }}" \
            -var="location=swedencentral" \
            -var="prefix=airflow" \
            -var="docker_image=${{ env.IMAGE_NAME }}" \
            -var="image_tag=${{ env.IMAGE_TAG }}" \
            -var="azure_credentials=${{ secrets.AZURE_CREDENTIALS_JSON }}" \
            -var='environment_variables={AIRFLOW_VAR_ENV="dev"}' \
            -var='tags={project="airflow"}' \
            -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev'
        working-directory: terraform/dev/acr
        run: |
          terraform apply \
            -input=false \
            -lock-timeout=120s \
            tfplan

  docker-build-push:
    name: Build and Push Docker Image
    needs: terraform-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}

      - name: ACR Login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Docker Build
        run: docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Docker Push
        run: docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  terraform-redeploy:
    name: Terraform Re-Apply with New Image
    needs: docker-build-push
    if: github.event.head_commit.message != 'skip-infra'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}

      - name: Break Terraform state blob lease if locked
        run: |
          az storage blob lease break \
            --account-name tfstate147025af \
            --container-name tfstate \
            --blob-name terraform.tfstate \
            --auth-mode login || echo "No lease to break"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform/dev/acr
        run: terraform init

      - name: Terraform Apply (New Image Tag)
        working-directory: terraform/dev/acr
        run: |
          terraform apply -auto-approve -lock-timeout=120s \
            -var="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" \
            -var="acr_name=${{ env.ACR_NAME }}" \
            -var="location=swedencentral" \
            -var="prefix=airflow" \
            -var="docker_image=${{ env.IMAGE_NAME }}" \
            -var="image_tag=${{ env.IMAGE_TAG }}" \
            -var="azure_credentials=${{ secrets.AZURE_CREDENTIALS_JSON }}" \
            -var='environment_variables={AIRFLOW_VAR_ENV="dev"}' \
            -var='tags={project="airflow"}'
