name: Deploy Airflow to Azure

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: airflow-custom
  IMAGE_TAG: latest_img
  ACR_NAME: acrairflowdevhealthcare
  ACR_LOGIN_SERVER: acrairflowdevhealthcare.azurecr.io
  RESOURCE_GROUP_NAME: healthcare_project
  CONTAINER_INSTANCE_NAME: airflowdev-aci
  LOCATION: swedencentral
  PREFIX: airflowdev

jobs:
  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}

      - name: Check ACR and Login or Create & Login
        run: |
          set -e
          ACR_NAME="${{ env.ACR_NAME }}"
          RESOURCE_GROUP="${{ env.RESOURCE_GROUP_NAME }}"
          LOCATION="${{ env.LOCATION }}"

          if az acr show --name "$ACR_NAME" --resource-group "$RESOURCE_GROUP" &>/dev/null; then
            echo "ACR $ACR_NAME exists. Logging in..."
            az acr login --name "$ACR_NAME"
          else
            echo "ACR $ACR_NAME does not exist. Creating..."
            az acr create --resource-group "$RESOURCE_GROUP" --name "$ACR_NAME" --sku Basic --location "$LOCATION" --admin-enabled false
            echo "ACR created. Logging in..."
            az acr login --name "$ACR_NAME"
          fi

      - name: Docker Build
        run: docker build -f Dockerfile -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Docker Push
        run: docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  terraform-deploy:
    name: Terraform Deploy Infrastructure
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}

      - name: Export ARM Auth Variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ACR_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ACR_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ACR_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Break Terraform State Lease
        run: |
          az storage blob lease break \
            --account-name tfstate147025af \
            --container-name tfstate \
            --blob-name terraform.tfstate \
            --auth-mode login || echo "No lease to break"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform/dev/acr
        run: terraform init

      - name: Terraform Format Check
        working-directory: terraform/dev/acr
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: terraform/dev/acr
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/dev/acr
        run: |
          terraform plan \
            -input=false \
            -lock-timeout=120s \
            -var="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" \
            -var="acr_name=${{ env.ACR_NAME }}" \
            -var="location=${{ env.LOCATION }}" \
            -var="prefix=${{ env.PREFIX }}" \
            -var="acr_sp_username=${{ secrets.ACR_SP_USERNAME }}" \
            -var="acr_sp_password=${{ secrets.ACR_SP_PASSWORD }}" \
            -var="docker_image=${{ env.IMAGE_NAME }}" \
            -var="image_tag=${{ env.IMAGE_TAG }}" \
            -var="ACR_CLIENT_ID=${{ secrets.ACR_CLIENT_ID }}" \
            -var="ACR_CLIENT_SECRET=${{ secrets.ACR_CLIENT_SECRET }}" \
            -var="ACR_TENANT_ID=${{ secrets.ACR_TENANT_ID }}" \
            -var="AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var='environment_variables={"AIRFLOW_VAR_ENV":"dev"}' \
            -var='tags={"project"="airflow"}' \
            -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev'
        working-directory: terraform/dev/acr
        run: terraform apply -input=false -lock-timeout=120s tfplan

      - name: Wait for Azure Container Instance to be ready
        run: |
          echo "Waiting for container instance '${{ env.CONTAINER_INSTANCE_NAME }}' to be ready..."
          for i in {1..30}; do
            az container show --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.CONTAINER_INSTANCE_NAME }} && break
            echo "Container not found yet, retrying in 10 seconds..."
            sleep 10
          done

      - name: Fetch Airflow Container Logs (Deploy)
        run: |
          echo "Fetching logs for Azure Container Instance '${{ env.CONTAINER_INSTANCE_NAME }}'..."
          az container logs --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.CONTAINER_INSTANCE_NAME }}

  terraform-redeploy:
    name: Terraform Re-Apply with New Image
    needs: terraform-deploy
    if: github.event.head_commit.message != 'skip-infra'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}

      - name: Export ARM Auth Variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ACR_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ACR_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ACR_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Break Terraform State Lease
        run: |
          az storage blob lease break \
            --account-name tfstate147025af \
            --container-name tfstate \
            --blob-name terraform.tfstate \
            --auth-mode login || echo "No lease to break"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform/dev/acr
        run: terraform init

      - name: Terraform Apply (New Image Tag)
        working-directory: terraform/dev/acr
        run: |
          terraform apply -auto-approve -lock-timeout=120s \
            -var="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" \
            -var="acr_name=${{ env.ACR_NAME }}" \
            -var="location=${{ env.LOCATION }}" \
            -var="prefix=${{ env.PREFIX }}" \
            -var="acr_sp_username=${{ secrets.ACR_SP_USERNAME }}" \
            -var="acr_sp_password=${{ secrets.ACR_SP_PASSWORD }}" \
            -var="docker_image=${{ env.IMAGE_NAME }}" \
            -var="image_tag=${{ env.IMAGE_TAG }}" \
            -var="ACR_CLIENT_ID=${{ secrets.ACR_CLIENT_ID }}" \
            -var="ACR_CLIENT_SECRET=${{ secrets.ACR_CLIENT_SECRET }}" \
            -var="ACR_TENANT_ID=${{ secrets.ACR_TENANT_ID }}" \
            -var="AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var='environment_variables={"AIRFLOW_VAR_ENV":"dev"}' \
            -var='tags={"project":"airflow"}'

      - name: Wait for Azure Container Instance to be ready (Redeploy)
        run: |
          echo "Waiting for container instance '${{ env.CONTAINER_INSTANCE_NAME }}' to be ready after redeploy..."
          for i in {1..30}; do
            az container show --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.CONTAINER_INSTANCE_NAME }} && break
            echo "Container not found yet, retrying in 10 seconds..."
            sleep 10
          done

      - name: Fetch Airflow Container Logs (Redeploy)
        run: |
          echo "Fetching logs for Azure Container Instance '${{ env.CONTAINER_INSTANCE_NAME }}' (redeploy)..."
          az container logs --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.CONTAINER_INSTANCE_NAME }}
