name: Deploy Airflow to Azure

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: airflow-custom
  IMAGE_TAG: latest_img
  ACR_NAME: acrairflowdevhealthcare
  RESOURCE_GROUP: healthcare_project
  CONTAINER_INSTANCE_NAME: airflow-container

jobs:
  terraform-deploy:
    name: Terraform Deploy Infrastructure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev]

    concurrency:
      group: terraform-${{ matrix.env }}
      cancel-in-progress: true

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Break Terraform state blob lease if any
        run: |
          az storage blob lease break \
            --account-name tfstate147025af \
            --container-name tfstate \
            --blob-name terraform.tfstate \
            --auth-mode login || echo "No lease to break"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform/${{ matrix.env }}/acr
        run: terraform init

      - name: Terraform Format Check
        working-directory: terraform/${{ matrix.env }}/acr
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: terraform/${{ matrix.env }}/acr
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/${{ matrix.env }}/acr
        run: terraform plan \
          -var "azure_credentials=${{ secrets.AZURE_CREDENTIALS_JSON }}" \
          -var "acr_sp_username=${{ secrets.ACR_SP_USERNAME }}" \
          -var "acr_sp_password=${{ secrets.ACR_SP_PASSWORD }}"

      - name: Terraform Apply
        if: ${{ github.ref == format('refs/heads/{0}', matrix.env) }}
        working-directory: terraform/${{ matrix.env }}/acr
        run: terraform apply -auto-approve \
          -var "azure_credentials=${{ secrets.AZURE_CREDENTIALS_JSON }}" \
          -var "acr_sp_username=${{ secrets.ACR_SP_USERNAME }}" \
          -var "acr_sp_password=${{ secrets.ACR_SP_PASSWORD }}"


  docker-build-push:
    name: Build and Push Docker Image
    needs: terraform-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Docker Build
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Docker Push
        run: |
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  terraform-redeploy:
    name: Terraform Re-Apply with New Image
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'skip-infra'
    strategy:
      matrix:
        env: [dev]

    concurrency:
      group: terraform-${{ matrix.env }}
      cancel-in-progress: true

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Break Terraform state blob lease if any
        run: |
          az storage blob lease break \
            --account-name tfstate147025af \
            --container-name tfstate \
            --blob-name terraform.tfstate \
            --auth-mode login || echo "No lease to break"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform/${{ matrix.env }}/acr
        run: terraform init

      - name: Terraform Apply with Image Tag
        working-directory: terraform/${{ matrix.env }}/acr
        run: |
          terraform apply -lock-timeout=120s -auto-approve \
          -var-file=terraform.tfvars \
          -var="image_tag=${{ env.IMAGE_TAG }}"

