name: Deploy Airflow to Azure

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: airflow-custom
  IMAGE_TAG: latest_img
  ACR_NAME: acrairflowdevhealthcare
  RESOURCE_GROUP: healthcare_project
  CONTAINER_INSTANCE_NAME: airflow-container

jobs:
  terraform-deploy:
    name: Terraform Deploy Infrastructure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform/${{ matrix.env }}/acr
        run: terraform init

      - name: Terraform Format Check
        working-directory: terraform/${{ matrix.env }}/acr
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: terraform/${{ matrix.env }}/acr
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/${{ matrix.env }}/acr
        run: |
          terraform plan -out=tfplan -var-file=terraform.tfvars \
            -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -var "azure_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -var "azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Terraform Apply
        if: ${{ github.ref == format('refs/heads/{0}', matrix.env) }}
        working-directory: terraform/${{ matrix.env }}/acr
        run: terraform apply -auto-approve tfplan

  docker-build-push:
    name: Build and Push Docker Image
    needs: terraform-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - ACR Login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Docker Build
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Docker Push
        run: |
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  terraform-redeploy:
    name: Terraform Re-Apply with New Image
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'skip-infra'
    strategy:
      matrix:
        env: [dev]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform/${{ matrix.env }}/acr
        run: terraform init

      - name: Terraform Apply with Image Tag
        working-directory: terraform/${{ matrix.env }}/acr
        run: |
          terraform apply -auto-approve -var-file=terraform.tfvars \
          -var "image_tag=${{ env.IMAGE_TAG }}" \
          -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var "azure_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
          -var "azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
          -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
